begin;

create extension if not exists pgcrypto;

-- Bootstrap-compatible base tables. These are intentionally minimal and only
-- created when a fresh Supabase project does not already have the platform schema.
create table if not exists public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  email text unique,
  role text not null default 'client',
  agency_id uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  full_name text,
  role text not null default 'client',
  agency_id uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.regions (
  id integer generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.cities (
  id integer generated by default as identity primary key,
  name text not null unique,
  region_id integer references public.regions(id) on delete set null,
  latitude double precision,
  longitude double precision,
  created_at timestamptz not null default now()
);

create table if not exists public.agencies (
  id uuid primary key default gen_random_uuid(),
  owner_user_id uuid references auth.users(id) on delete set null,
  email text,
  name text not null,
  city_id integer references public.cities(id) on delete set null,
  region text,
  address text,
  phone text,
  whatsapp text,
  description text,
  status text not null default 'active',
  is_verified boolean not null default false,
  logo_url text,
  cover_url text,
  latitude double precision,
  longitude double precision,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.cars (
  id uuid primary key default gen_random_uuid(),
  agency_id uuid not null references public.agencies(id) on delete cascade,
  brand text not null,
  model text not null,
  year integer,
  price_per_day numeric(12,2) not null default 0,
  availability text not null default 'available',
  status text not null default 'active',
  views_count integer not null default 0,
  whatsapp_clicks integer not null default 0,
  phone_clicks integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.car_images (
  id uuid primary key default gen_random_uuid(),
  car_id uuid not null references public.cars(id) on delete cascade,
  image_url text not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.reservations (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete set null,
  agency_id uuid references public.agencies(id) on delete cascade,
  car_id uuid references public.cars(id) on delete cascade,
  status text not null default 'pending',
  start_date date not null,
  end_date date not null,
  total_amount numeric(12,2) not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.reviews (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade,
  agency_id uuid references public.agencies(id) on delete cascade,
  car_id uuid references public.cars(id) on delete cascade,
  rating integer,
  comment text,
  created_at timestamptz not null default now()
);

create table if not exists public.favorites (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  car_id uuid not null references public.cars(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (user_id, car_id)
);

create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade,
  type text,
  title text,
  message text,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.activity_logs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete set null,
  action text not null,
  target_type text,
  target_id uuid,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.agency_documents (
  id uuid primary key default gen_random_uuid(),
  agency_id uuid not null references public.agencies(id) on delete cascade,
  document_type text,
  file_url text,
  status text not null default 'pending',
  created_at timestamptz not null default now()
);

create table if not exists public.subscriptions (
  id uuid primary key default gen_random_uuid(),
  agency_id uuid references public.agencies(id) on delete cascade,
  plan_name text,
  status text not null default 'active',
  starts_at timestamptz,
  ends_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.payments (
  id uuid primary key default gen_random_uuid(),
  agency_id uuid references public.agencies(id) on delete set null,
  subscription_id uuid references public.subscriptions(id) on delete set null,
  amount numeric(12,2) not null default 0,
  currency text not null default 'MAD',
  status text not null default 'pending',
  provider_reference text,
  created_at timestamptz not null default now()
);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'users_agency_id_fkey'
  ) then
    alter table public.users
      add constraint users_agency_id_fkey
      foreign key (agency_id)
      references public.agencies(id)
      on delete set null;
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'profiles_agency_id_fkey'
  ) then
    alter table public.profiles
      add constraint profiles_agency_id_fkey
      foreign key (agency_id)
      references public.agencies(id)
      on delete set null;
  end if;
end;
$$;

do $$
declare
  required_table text;
  required_tables text[] := array[
    'public.agencies',
    'public.cars',
    'public.cities',
    'public.regions',
    'public.reservations'
  ];
begin
  foreach required_table in array required_tables loop
    if to_regclass(required_table) is null then
      raise exception using
        errcode = 'P0001',
        message = format(
          'Owner dashboard migration prerequisite failed: required table %s does not exist. Apply your base car-rental schema first, or run this against the correct Supabase project.',
          required_table
        );
    end if;
  end loop;

  if to_regclass('public.users') is null and to_regclass('public.profiles') is null then
    raise exception using
      errcode = 'P0001',
      message = 'Owner dashboard migration prerequisite failed: neither public.users nor public.profiles exists. The migration needs one app-level identity table in addition to auth.users.';
  end if;
end;
$$;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.current_app_role()
returns text
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  role_value text;
begin
  if auth.uid() is null then
    return null;
  end if;

  if to_regclass('public.profiles') is not null
     and exists (
       select 1
       from information_schema.columns
       where table_schema = 'public'
         and table_name = 'profiles'
         and column_name = 'role'
     ) then
    execute 'select role::text from public.profiles where id = $1 limit 1'
      into role_value
      using auth.uid();
  end if;

  if role_value is null
     and to_regclass('public.users') is not null
     and exists (
       select 1
       from information_schema.columns
       where table_schema = 'public'
         and table_name = 'users'
         and column_name = 'role'
     ) then
    execute 'select role::text from public.users where id = $1 limit 1'
      into role_value
      using auth.uid();
  end if;

  return role_value;
end;
$$;

create or replace function public.is_super_owner()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.current_app_role() = 'super_owner';
$$;

create or replace function public.current_agency_ids()
returns uuid[]
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  agency_ids uuid[] := '{}'::uuid[];
begin
  if auth.uid() is null then
    return agency_ids;
  end if;

  if to_regclass('public.agencies') is not null
     and exists (
       select 1 from information_schema.columns
       where table_schema = 'public'
         and table_name = 'agencies'
         and column_name = 'owner_user_id'
     ) then
    execute 'select coalesce(array_agg(id), ''{}''::uuid[]) from public.agencies where owner_user_id = $1'
      into agency_ids
      using auth.uid();
  end if;

  if coalesce(array_length(agency_ids, 1), 0) = 0
     and to_regclass('public.profiles') is not null
     and exists (
       select 1 from information_schema.columns
       where table_schema = 'public'
         and table_name = 'profiles'
         and column_name = 'agency_id'
     ) then
    execute '
      select case
        when agency_id is null then ''{}''::uuid[]
        else array[agency_id]
      end
      from public.profiles
      where id = $1
      limit 1
    '
      into agency_ids
      using auth.uid();
  end if;

  if coalesce(array_length(agency_ids, 1), 0) = 0
     and to_regclass('public.users') is not null
     and exists (
       select 1 from information_schema.columns
       where table_schema = 'public'
         and table_name = 'users'
         and column_name = 'agency_id'
     ) then
    execute '
      select case
        when agency_id is null then ''{}''::uuid[]
        else array[agency_id]
      end
      from public.users
      where id = $1
      limit 1
    '
      into agency_ids
      using auth.uid();
  end if;

  return coalesce(agency_ids, '{}'::uuid[]);
end;
$$;

create or replace function public.can_access_agency(target_agency_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.is_super_owner()
    or target_agency_id = any(public.current_agency_ids());
$$;

create or replace function public.sync_identity_role(
  target_user_id uuid,
  target_email text,
  target_role text,
  target_agency_id uuid default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if to_regclass('public.users') is not null then
    if exists (
      select 1
      from information_schema.columns
      where table_schema = 'public'
        and table_name = 'users'
        and column_name = 'agency_id'
    ) then
      execute '
        insert into public.users (id, email, role, agency_id)
        values ($1, $2, $3, $4)
        on conflict (id) do update
        set email = excluded.email,
            role = excluded.role,
            agency_id = excluded.agency_id
      '
      using target_user_id, target_email, target_role, target_agency_id;
    else
      execute '
        insert into public.users (id, email, role)
        values ($1, $2, $3)
        on conflict (id) do update
        set email = excluded.email,
            role = excluded.role
      '
      using target_user_id, target_email, target_role;
    end if;
  end if;

  if to_regclass('public.profiles') is not null
     and exists (
       select 1
       from information_schema.columns
       where table_schema = 'public'
         and table_name = 'profiles'
         and column_name = 'role'
     ) then
    if exists (
      select 1
      from information_schema.columns
      where table_schema = 'public'
        and table_name = 'profiles'
        and column_name = 'agency_id'
    ) then
      execute '
        update public.profiles
        set role = $2,
            agency_id = coalesce($3, agency_id)
        where id = $1
      '
      using target_user_id, target_role, target_agency_id;
    else
      execute '
        update public.profiles
        set role = $2
        where id = $1
      '
      using target_user_id, target_role;
    end if;
  end if;
end;
$$;

alter table if exists public.agencies
  add column if not exists owner_user_id uuid,
  add column if not exists status text not null default 'active',
  add column if not exists is_verified boolean not null default false,
  add column if not exists logo_url text,
  add column if not exists cover_url text,
  add column if not exists latitude double precision,
  add column if not exists longitude double precision;

alter table if exists public.cars
  add column if not exists status text not null default 'active',
  add column if not exists views_count integer not null default 0,
  add column if not exists whatsapp_clicks integer not null default 0,
  add column if not exists phone_clicks integer not null default 0;

do $$
begin
  if to_regclass('public.agencies') is not null
     and not exists (
       select 1
       from pg_constraint
       where conname = 'agencies_owner_user_id_fkey'
     ) then
    alter table public.agencies
      add constraint agencies_owner_user_id_fkey
      foreign key (owner_user_id)
      references auth.users(id)
      on delete set null;
  end if;
end;
$$;

create index if not exists agencies_owner_user_id_idx on public.agencies(owner_user_id);
create index if not exists agencies_status_verified_idx on public.agencies(status, is_verified);
create index if not exists cars_agency_status_idx on public.cars(agency_id, status);
create index if not exists cars_status_availability_idx on public.cars(status, availability);

create table if not exists public.traffic_events (
  id uuid primary key default gen_random_uuid(),
  city_id int references public.cities(id) on delete set null,
  agency_id uuid references public.agencies(id) on delete set null,
  car_id uuid references public.cars(id) on delete set null,
  user_id uuid references auth.users(id) on delete set null,
  event_type text not null,
  event_source text,
  ip_address inet,
  user_agent text,
  latitude double precision,
  longitude double precision,
  created_at timestamptz not null default now()
);

create table if not exists public.agency_permissions (
  id uuid primary key default gen_random_uuid(),
  agency_id uuid not null references public.agencies(id) on delete cascade,
  can_add_cars boolean not null default true,
  can_edit_cars boolean not null default true,
  can_delete_cars boolean not null default true,
  can_manage_reservations boolean not null default true,
  can_upload_images boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (agency_id)
);

create table if not exists public.agency_status_history (
  id uuid primary key default gen_random_uuid(),
  agency_id uuid not null references public.agencies(id) on delete cascade,
  old_status text,
  new_status text,
  changed_by uuid references auth.users(id) on delete set null,
  reason text,
  created_at timestamptz not null default now()
);

create table if not exists public.admin_audit_logs (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  action text not null,
  target_type text,
  target_id uuid,
  details jsonb not null default '{}'::jsonb,
  ip_address inet,
  created_at timestamptz not null default now()
);

create table if not exists public.owner_notifications (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  type text,
  title text,
  message text,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists traffic_events_city_created_idx on public.traffic_events(city_id, created_at desc);
create index if not exists traffic_events_agency_created_idx on public.traffic_events(agency_id, created_at desc);
create index if not exists traffic_events_car_created_idx on public.traffic_events(car_id, created_at desc);
create index if not exists traffic_events_type_created_idx on public.traffic_events(event_type, created_at desc);
create index if not exists agency_status_history_agency_created_idx on public.agency_status_history(agency_id, created_at desc);
create index if not exists admin_audit_logs_owner_created_idx on public.admin_audit_logs(owner_id, created_at desc);
create index if not exists owner_notifications_owner_read_idx on public.owner_notifications(owner_id, is_read, created_at desc);

drop trigger if exists agency_permissions_set_updated_at on public.agency_permissions;
create trigger agency_permissions_set_updated_at
before update on public.agency_permissions
for each row
execute function public.set_updated_at();

do $$
declare
  reservation_amount_expr text := '0::numeric';
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'reservations' and column_name = 'total_amount'
  ) then
    reservation_amount_expr := 'coalesce(r.total_amount, 0)::numeric';
  elsif exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'reservations' and column_name = 'total_price'
  ) then
    reservation_amount_expr := 'coalesce(r.total_price, 0)::numeric';
  elsif exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'reservations' and column_name = 'amount'
  ) then
    reservation_amount_expr := 'coalesce(r.amount, 0)::numeric';
  elsif exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'reservations' and column_name = 'total'
  ) then
    reservation_amount_expr := 'coalesce(r.total, 0)::numeric';
  end if;

  execute format($view$
    create or replace view public.car_stats_view as
    select
      c.id as car_id,
      c.agency_id,
      count(r.id) filter (where r.status in ('accepted', 'completed'))::bigint as total_reservations,
      coalesce(
        sum(greatest((coalesce(r.end_date::date, r.start_date::date) - r.start_date::date), 1))
          filter (where r.status in ('accepted', 'completed')),
        0
      )::bigint as total_rental_days,
      coalesce(
        sum(%1$s) filter (where r.status in ('accepted', 'completed')),
        0
      )::numeric(14,2) as total_revenue,
      max(coalesce(r.end_date::timestamptz, r.created_at)) filter (where r.status in ('accepted', 'completed')) as last_rented_at,
      coalesce(c.views_count, 0)::bigint as views_count,
      coalesce(c.whatsapp_clicks, 0)::bigint as whatsapp_clicks,
      coalesce(c.phone_clicks, 0)::bigint as phone_clicks
    from public.cars c
    left join public.reservations r on r.car_id = c.id
    group by c.id;
  $view$, reservation_amount_expr);
end;
$$;

create or replace view public.agency_stats_view as
select
  a.id as agency_id,
  count(c.id)::bigint as total_cars,
  count(c.id) filter (where coalesce(c.availability, 'available') = 'available' and coalesce(c.status, 'active') = 'active')::bigint as available_cars,
  count(c.id) filter (where coalesce(c.availability, 'available') = 'rented' and coalesce(c.status, 'active') = 'active')::bigint as rented_cars,
  coalesce(sum(cs.total_reservations), 0)::bigint as total_reservations,
  coalesce(sum(cs.total_rental_days), 0)::bigint as total_rental_days,
  coalesce(sum(cs.total_revenue), 0)::numeric(14,2) as total_revenue,
  coalesce(sum(cs.views_count), 0)::bigint as views_count,
  coalesce(sum(cs.whatsapp_clicks), 0)::bigint as whatsapp_clicks,
  coalesce(sum(cs.phone_clicks), 0)::bigint as phone_clicks
from public.agencies a
left join public.cars c on c.agency_id = a.id
left join public.car_stats_view cs on cs.car_id = c.id
group by a.id;

create or replace view public.city_stats_view as
select
  city.id as city_id,
  count(distinct a.id)::bigint as total_agencies,
  count(distinct c.id)::bigint as total_cars,
  count(distinct c.id) filter (where coalesce(c.availability, 'available') = 'available' and coalesce(c.status, 'active') = 'active')::bigint as available_cars,
  coalesce(sum(cs.total_reservations), 0)::bigint as total_reservations,
  coalesce(sum(cs.total_revenue), 0)::numeric(14,2) as total_revenue,
  count(te.id)::bigint as total_traffic,
  coalesce(sum(cs.whatsapp_clicks), 0)::bigint as whatsapp_clicks,
  coalesce(sum(cs.phone_clicks), 0)::bigint as phone_clicks
from public.cities city
left join public.agencies a on a.city_id = city.id
left join public.cars c on c.agency_id = a.id
left join public.car_stats_view cs on cs.car_id = c.id
left join public.traffic_events te on te.city_id = city.id
group by city.id;

create or replace view public.owner_agencies_view as
with traffic_by_agency as (
  select
    agency_id,
    count(*)::bigint as total_traffic
  from public.traffic_events
  where agency_id is not null
  group by agency_id
)
select
  a.id,
  a.owner_user_id,
  a.email,
  coalesce(a.name, '') as name,
  a.logo_url as logo,
  a.cover_url as cover_image,
  a.city_id,
  c.name as city_name,
  coalesce(r.name, a.region, '') as region,
  a.address,
  a.phone,
  a.whatsapp,
  a.description,
  a.latitude,
  a.longitude,
  a.status,
  a.is_verified as verified,
  coalesce(ast.total_cars, 0)::bigint as cars_count,
  coalesce(ast.total_reservations, 0)::bigint as reservations_count,
  coalesce(ast.total_revenue, 0)::numeric(14,2) as estimated_revenue,
  coalesce(ast.views_count, 0)::bigint as views,
  case
    when coalesce(t.total_traffic, 0) = 0 then 0::numeric
    else round((coalesce(ast.total_reservations, 0)::numeric / t.total_traffic::numeric) * 100, 2)
  end as conversion_rate
from public.agencies a
left join public.cities c on c.id = a.city_id
left join public.regions r on r.id = c.region_id
left join public.agency_stats_view ast on ast.agency_id = a.id
left join traffic_by_agency t on t.agency_id = a.id;

create or replace view public.owner_cars_view as
select
  car.id,
  car.agency_id,
  a.name as agency_name,
  a.city_id,
  c.name as city_name,
  coalesce(
    array_remove(array_agg(ci.image_url order by ci.id), null),
    '{}'::text[]
  ) as photos,
  car.brand,
  car.model,
  car.year,
  car.price_per_day,
  coalesce(car.availability, 'available') as availability,
  coalesce(cs.total_reservations, 0)::bigint as reservations_count,
  coalesce(cs.total_rental_days, 0)::bigint as total_rented_days,
  coalesce(cs.total_revenue, 0)::numeric(14,2) as estimated_revenue,
  coalesce(cs.views_count, 0)::bigint as views,
  coalesce(cs.whatsapp_clicks, 0)::bigint as whatsapp_clicks,
  coalesce(cs.phone_clicks, 0)::bigint as phone_clicks,
  car.status
from public.cars car
join public.agencies a on a.id = car.agency_id
left join public.cities c on c.id = a.city_id
left join public.car_images ci on ci.car_id = car.id
left join public.car_stats_view cs on cs.car_id = car.id
group by
  car.id,
  a.name,
  a.city_id,
  c.name,
  cs.total_reservations,
  cs.total_rental_days,
  cs.total_revenue,
  cs.views_count,
  cs.whatsapp_clicks,
  cs.phone_clicks;

create or replace view public.owner_cities_view as
select
  city.id,
  city.name,
  coalesce(region.name, '') as region,
  coalesce(csv.total_agencies, 0)::bigint as agencies_count,
  coalesce(csv.total_cars, 0)::bigint as cars_count,
  coalesce(csv.total_reservations, 0)::bigint as reservations_count,
  coalesce(csv.total_traffic, 0)::bigint as traffic_count,
  city.latitude,
  city.longitude,
  coalesce(csv.total_revenue, 0)::numeric(14,2) as revenue
from public.cities city
left join public.regions region on region.id = city.region_id
left join public.city_stats_view csv on csv.city_id = city.id;

create or replace view public.city_traffic_metrics as
with traffic_rollup as (
  select
    te.city_id,
    count(*)::bigint as visitors,
    count(*) filter (where te.event_type = 'search')::bigint as searches,
    count(*) filter (where te.event_type in ('car_view', 'view'))::bigint as car_views,
    count(*) filter (where te.event_type = 'whatsapp_click')::bigint as whatsapp_clicks,
    count(*) filter (where te.event_type = 'phone_click')::bigint as phone_clicks
  from public.traffic_events te
  group by te.city_id
)
select
  city.id as city_id,
  city.name as city_name,
  coalesce(region.name, '') as region,
  city.latitude,
  city.longitude,
  coalesce(tr.visitors, 0)::bigint as visitors,
  coalesce(tr.searches, 0)::bigint as searches,
  coalesce(tr.car_views, 0)::bigint as car_views,
  coalesce(tr.whatsapp_clicks, csv.whatsapp_clicks, 0)::bigint as whatsapp_clicks,
  coalesce(tr.phone_clicks, csv.phone_clicks, 0)::bigint as phone_clicks,
  coalesce(csv.total_reservations, 0)::bigint as reservations,
  case
    when coalesce(tr.visitors, 0) = 0 then 0::numeric
    else round((coalesce(csv.total_reservations, 0)::numeric / tr.visitors::numeric) * 100, 2)
  end as conversion_rate,
  coalesce(csv.total_agencies, 0)::bigint as agencies_count,
  coalesce(csv.total_cars, 0)::bigint as cars_count,
  coalesce(csv.total_revenue, 0)::numeric(14,2) as revenue
from public.cities city
left join public.regions region on region.id = city.region_id
left join public.city_stats_view csv on csv.city_id = city.id
left join traffic_rollup tr on tr.city_id = city.id;

create or replace function public.get_owner_dashboard_stats()
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  with totals as (
    select
      count(*) filter (where a.status = 'active')::bigint as active_agencies,
      count(*) filter (where a.status = 'suspended')::bigint as suspended_agencies,
      count(*)::bigint as total_agencies
    from public.agencies a
  ),
  cars as (
    select
      count(*)::bigint as total_cars,
      count(*) filter (where coalesce(availability, 'available') = 'available' and status = 'active')::bigint as available_cars,
      count(*) filter (where coalesce(availability, 'available') = 'rented' and status = 'active')::bigint as rented_cars
    from public.cars
  ),
  reservations as (
    select
      coalesce(sum(total_reservations), 0)::bigint as total_reservations,
      coalesce(sum(total_revenue), 0)::numeric(14,2) as estimated_revenue
    from public.car_stats_view
  ),
  cities as (
    select count(*)::bigint as total_cities from public.cities
  ),
  traffic as (
    select count(*)::bigint as total_traffic from public.traffic_events
  )
  select jsonb_build_object(
    'totalAgencies', totals.total_agencies,
    'totalCars', cars.total_cars,
    'totalCities', cities.total_cities,
    'totalReservations', reservations.total_reservations,
    'availableCars', cars.available_cars,
    'rentedCars', cars.rented_cars,
    'estimatedRevenue', reservations.estimated_revenue,
    'totalTraffic', traffic.total_traffic,
    'activeAgencies', totals.active_agencies,
    'suspendedAgencies', totals.suspended_agencies
  )
  from totals, cars, reservations, cities, traffic;
$$;

create or replace function public.get_reservations_by_month()
returns table(name text, value bigint)
language sql
stable
security definer
set search_path = public
as $$
  select
    to_char(date_trunc('month', created_at), 'Mon') as name,
    count(*)::bigint as value
  from public.reservations
  where status in ('accepted', 'completed')
    and created_at >= date_trunc('year', now())
  group by 1, date_trunc('month', created_at)
  order by date_trunc('month', created_at);
$$;

create or replace function public.get_top_cities()
returns table(name text, value bigint)
language sql
stable
security definer
set search_path = public
as $$
  select name, reservations_count::bigint as value
  from public.owner_cities_view
  order by reservations_count desc, name asc
  limit 8;
$$;

create or replace function public.get_top_agencies()
returns table(name text, value bigint)
language sql
stable
security definer
set search_path = public
as $$
  select name, reservations_count::bigint as value
  from public.owner_agencies_view
  order by reservations_count desc, name asc
  limit 8;
$$;

create or replace function public.get_top_rented_cars()
returns table(name text, value bigint)
language sql
stable
security definer
set search_path = public
as $$
  select concat_ws(' ', brand, model) as name, reservations_count::bigint as value
  from public.owner_cars_view
  order by reservations_count desc, name asc
  limit 8;
$$;

create or replace function public.get_revenue_by_city()
returns table(name text, value numeric)
language sql
stable
security definer
set search_path = public
as $$
  select city.name, coalesce(csv.total_revenue, 0)::numeric as value
  from public.cities city
  left join public.city_stats_view csv on csv.city_id = city.id
  order by value desc, city.name asc
  limit 10;
$$;

create or replace function public.get_city_traffic_charts(selected_city_id int)
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  with trend as (
    select
      to_char(date_trunc('month', te.created_at), 'Mon') as name,
      count(*)::bigint as value
    from public.traffic_events te
    where te.city_id = selected_city_id
      and te.created_at >= date_trunc('year', now())
    group by 1, date_trunc('month', te.created_at)
    order by date_trunc('month', te.created_at)
  ),
  metrics as (
    select
      count(*) filter (where te.event_type = 'search')::bigint as searches,
      count(*) filter (where te.event_type in ('car_view', 'view'))::bigint as views,
      count(*) filter (where te.event_type in ('whatsapp_click', 'phone_click'))::bigint as clicks
    from public.traffic_events te
    where te.city_id = selected_city_id
  )
  select jsonb_build_object(
    'trend',
    coalesce((select jsonb_agg(jsonb_build_object('name', trend.name, 'value', trend.value)) from trend), '[]'::jsonb),
    'channelMix',
    jsonb_build_array(
      jsonb_build_object('name', 'Searches', 'value', coalesce((select searches from metrics), 0)),
      jsonb_build_object('name', 'Views', 'value', coalesce((select views from metrics), 0)),
      jsonb_build_object('name', 'Clicks', 'value', coalesce((select clicks from metrics), 0))
    )
  );
$$;

alter table public.traffic_events enable row level security;
alter table public.agency_permissions enable row level security;
alter table public.agency_status_history enable row level security;
alter table public.admin_audit_logs enable row level security;
alter table public.owner_notifications enable row level security;
alter table if exists public.agencies enable row level security;
alter table if exists public.cars enable row level security;
alter table if exists public.car_images enable row level security;
alter table if exists public.reservations enable row level security;
alter table if exists public.favorites enable row level security;
alter table if exists public.agency_documents enable row level security;

drop policy if exists traffic_events_super_owner_all on public.traffic_events;
create policy traffic_events_super_owner_all
on public.traffic_events
for all
to authenticated
using (public.is_super_owner())
with check (public.is_super_owner());

drop policy if exists agency_permissions_super_owner_all on public.agency_permissions;
create policy agency_permissions_super_owner_all
on public.agency_permissions
for all
to authenticated
using (public.is_super_owner())
with check (public.is_super_owner());

drop policy if exists agency_permissions_agency_read_own on public.agency_permissions;
create policy agency_permissions_agency_read_own
on public.agency_permissions
for select
to authenticated
using (public.can_access_agency(agency_id));

drop policy if exists agency_status_history_super_owner_all on public.agency_status_history;
create policy agency_status_history_super_owner_all
on public.agency_status_history
for all
to authenticated
using (public.is_super_owner())
with check (public.is_super_owner());

drop policy if exists agency_status_history_agency_read_own on public.agency_status_history;
create policy agency_status_history_agency_read_own
on public.agency_status_history
for select
to authenticated
using (public.can_access_agency(agency_id));

drop policy if exists admin_audit_logs_super_owner_all on public.admin_audit_logs;
create policy admin_audit_logs_super_owner_all
on public.admin_audit_logs
for all
to authenticated
using (public.is_super_owner())
with check (public.is_super_owner());

drop policy if exists owner_notifications_super_owner_all on public.owner_notifications;
create policy owner_notifications_super_owner_all
on public.owner_notifications
for all
to authenticated
using (public.is_super_owner())
with check (public.is_super_owner());

drop policy if exists owner_notifications_owner_read_own on public.owner_notifications;
create policy owner_notifications_owner_read_own
on public.owner_notifications
for select
to authenticated
using (owner_id = auth.uid());

drop policy if exists owner_notifications_owner_update_own on public.owner_notifications;
create policy owner_notifications_owner_update_own
on public.owner_notifications
for update
to authenticated
using (owner_id = auth.uid())
with check (owner_id = auth.uid());

drop policy if exists agencies_super_owner_all on public.agencies;
create policy agencies_super_owner_all
on public.agencies
for all
to authenticated
using (public.is_super_owner())
with check (public.is_super_owner());

drop policy if exists agencies_public_read_active_verified on public.agencies;
create policy agencies_public_read_active_verified
on public.agencies
for select
to anon, authenticated
using (status = 'active' and is_verified = true);

drop policy if exists agencies_agency_manage_own on public.agencies;
create policy agencies_agency_manage_own
on public.agencies
for all
to authenticated
using (public.can_access_agency(id))
with check (public.can_access_agency(id));

drop policy if exists cars_super_owner_all on public.cars;
create policy cars_super_owner_all
on public.cars
for all
to authenticated
using (public.is_super_owner())
with check (public.is_super_owner());

drop policy if exists cars_public_read_active_available on public.cars;
create policy cars_public_read_active_available
on public.cars
for select
to anon, authenticated
using (
  status = 'active'
  and coalesce(availability, 'available') = 'available'
  and exists (
    select 1
    from public.agencies a
    where a.id = cars.agency_id
      and a.status = 'active'
      and a.is_verified = true
  )
);

drop policy if exists cars_agency_manage_own on public.cars;
create policy cars_agency_manage_own
on public.cars
for all
to authenticated
using (exists (
  select 1
  from public.agencies a
  where a.id = cars.agency_id
    and public.can_access_agency(a.id)
))
with check (exists (
  select 1
  from public.agencies a
  where a.id = cars.agency_id
    and public.can_access_agency(a.id)
));

drop policy if exists car_images_super_owner_all on public.car_images;
create policy car_images_super_owner_all
on public.car_images
for all
to authenticated
using (public.is_super_owner())
with check (public.is_super_owner());

drop policy if exists car_images_public_read_for_public_cars on public.car_images;
create policy car_images_public_read_for_public_cars
on public.car_images
for select
to anon, authenticated
using (
  exists (
    select 1
    from public.cars c
    join public.agencies a on a.id = c.agency_id
    where c.id = car_images.car_id
      and c.status = 'active'
      and coalesce(c.availability, 'available') = 'available'
      and a.status = 'active'
      and a.is_verified = true
  )
);

drop policy if exists car_images_agency_manage_own on public.car_images;
create policy car_images_agency_manage_own
on public.car_images
for all
to authenticated
using (
  exists (
    select 1
    from public.cars c
    join public.agencies a on a.id = c.agency_id
    where c.id = car_images.car_id
      and public.can_access_agency(a.id)
  )
)
with check (
  exists (
    select 1
    from public.cars c
    join public.agencies a on a.id = c.agency_id
    where c.id = car_images.car_id
      and public.can_access_agency(a.id)
  )
);

drop policy if exists reservations_super_owner_all on public.reservations;
create policy reservations_super_owner_all
on public.reservations
for all
to authenticated
using (public.is_super_owner())
with check (public.is_super_owner());

drop policy if exists reservations_client_manage_own on public.reservations;
create policy reservations_client_manage_own
on public.reservations
for all
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists reservations_agency_manage_own on public.reservations;
create policy reservations_agency_manage_own
on public.reservations
for all
to authenticated
using (exists (
  select 1
  from public.agencies a
  where a.id = reservations.agency_id
    and public.can_access_agency(a.id)
))
with check (exists (
  select 1
  from public.agencies a
  where a.id = reservations.agency_id
    and public.can_access_agency(a.id)
));

drop policy if exists favorites_super_owner_all on public.favorites;
create policy favorites_super_owner_all
on public.favorites
for all
to authenticated
using (public.is_super_owner())
with check (public.is_super_owner());

drop policy if exists favorites_client_manage_own on public.favorites;
create policy favorites_client_manage_own
on public.favorites
for all
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists agency_documents_super_owner_all on public.agency_documents;
create policy agency_documents_super_owner_all
on public.agency_documents
for all
to authenticated
using (public.is_super_owner())
with check (public.is_super_owner());

drop policy if exists agency_documents_agency_manage_own on public.agency_documents;
create policy agency_documents_agency_manage_own
on public.agency_documents
for all
to authenticated
using (public.can_access_agency(agency_id))
with check (public.can_access_agency(agency_id));

insert into public.regions (name)
select region_name
from (
  values
    ('Casablanca-Settat'),
    ('Rabat-Sale-Kenitra'),
    ('Marrakech-Safi'),
    ('Tanger-Tetouan-Al Hoceima'),
    ('Fes-Meknes'),
    ('Souss-Massa'),
    ('Oriental'),
    ('Beni Mellal-Khenifra'),
    ('Laayoune-Sakia El Hamra'),
    ('Dakhla-Oued Ed-Dahab')
) as seed(region_name)
where not exists (
  select 1 from public.regions r where lower(r.name) = lower(seed.region_name)
);

insert into public.cities (name, region_id, latitude, longitude)
select city_name, region.id, latitude, longitude
from (
  values
    ('Casablanca', 'Casablanca-Settat', 33.5731, -7.5898),
    ('Rabat', 'Rabat-Sale-Kenitra', 34.0209, -6.8416),
    ('Marrakech', 'Marrakech-Safi', 31.6295, -7.9811),
    ('Tanger', 'Tanger-Tetouan-Al Hoceima', 35.7595, -5.8340),
    ('Fes', 'Fes-Meknes', 34.0331, -5.0003),
    ('Agadir', 'Souss-Massa', 30.4278, -9.5981),
    ('Meknes', 'Fes-Meknes', 33.8731, -5.5407),
    ('Oujda', 'Oriental', 34.6814, -1.9086),
    ('Tetouan', 'Tanger-Tetouan-Al Hoceima', 35.5889, -5.3626),
    ('Kenitra', 'Rabat-Sale-Kenitra', 34.2610, -6.5802),
    ('El Jadida', 'Casablanca-Settat', 33.2316, -8.5007),
    ('Essaouira', 'Marrakech-Safi', 31.5085, -9.7595),
    ('Nador', 'Oriental', 35.1688, -2.9335),
    ('Safi', 'Marrakech-Safi', 32.2994, -9.2372),
    ('Beni Mellal', 'Beni Mellal-Khenifra', 32.3373, -6.3498),
    ('Laayoune', 'Laayoune-Sakia El Hamra', 27.1536, -13.2033),
    ('Dakhla', 'Dakhla-Oued Ed-Dahab', 23.6848, -15.9570)
) as seed(city_name, region_name, latitude, longitude)
join public.regions region on lower(region.name) = lower(seed.region_name)
where not exists (
  select 1 from public.cities c where lower(c.name) = lower(seed.city_name)
);

commit;
